<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5KP1IVJ" failures="0" tests="3" name="Apptest.AppiumAppFramework.eCommerce_tc_1" time="0.054" errors="1" timestamp="2024-08-27T10:40:25 IST" skipped="2">
  <testcase classname="Apptest.AppiumAppFramework.eCommerce_tc_1" name="fillform_ErrorValidation" time="0.000">
    <skipped/>
  </testcase> <!-- fillform_ErrorValidation -->
  <system-out/>
  <testcase classname="Apptest.AppiumAppFramework.eCommerce_tc_1" name="fillform_PositiveTest" time="0.000">
    <skipped/>
  </testcase> <!-- fillform_PositiveTest -->
  <system-out/>
  <testcase classname="Apptest.AppiumAppFramework.eCommerce_tc_1" name="preSetup" time="0.054">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Apptest.AppiumAppFramework.eCommerce_tc_1.preSetup(eCommerce_tc_1.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- preSetup -->
  <system-out/>
</testsuite> <!-- Apptest.AppiumAppFramework.eCommerce_tc_1 -->
